sudo: false
language: node_js
cache: npm
node_js:
  - 8
  - 10
  - node
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run test:report
  - npm run release
